version: '3.8'

services:
  simplecrud_database_mysql:
    image: mysql:8.0.31
    container_name: simplecrud_database_mysql
    environment:
      MYSQL_ROOT_PASSWORD: simplecrudpassroot
      MYSQL_USER: simplecruduser
      MYSQL_PASSWORD: simplecrudpass
      MYSQL_DATABASE: simplecrud
    ports:
      - "3306:3306"