version: '3.8'

services:
  simplecrud_database_mysql:
    image: mysql:8.0.31
    container_name: simplecrud_database_mysql
    environment:
      MYSQL_ROOT_PASSWORD: simplecrudpassroot
      MYSQL_USER: simplecruduser
      MYSQL_PASSWORD: simplecrudpass
      MYSQL_DATABASE: simplecrud
    ports:
      - "3306:3306"
  
  simplecrud_database_mongo:
    image: mongo:latest
    container_name: simplecrud_database_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: simplecrudroot
      MONGO_INITDB_ROOT_PASSWORD: simplecrudpass
      MONGO_INITDB_DATABASE: simplecrudusers
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"